// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 OpenMasjid-Solutions

/**
 * Every source file in this repository carries an SPDX header. CLAUDE.md §2 makes that a
 * hard rule, and `OpenMasjidAPPS/docs/APP_LICENSING.md` §5 makes it the org's policy for
 * every official app — but a rule written in a document is a rule nobody notices breaking
 * until an audit, and by then the file has been shipped in an image under a licence it
 * never declared.
 *
 * So the rule is asserted, by the test suite, against the actual tree. It walks the whole
 * repository rather than just `server/`, because the web half, the workflows and the
 * compose are exactly as covered by AGPL-3.0 and exactly as easy to forget.
 *
 * If this fails: add the two-line header in that file's comment syntax —
 *
 *   .ts .tsx .js .cjs .mjs .css   // SPDX-License-Identifier: AGPL-3.0-only
 *   .yml .yaml .sh Dockerfile     # SPDX-License-Identifier: AGPL-3.0-only
 *   .md .html                     <!-- SPDX-License-Identifier: AGPL-3.0-only -->
 *
 * followed by `Copyright (C) 2026 OpenMasjid-Solutions` in the same syntax.
 */
import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import path from 'node:path';

const REPO = path.resolve(__dirname, '..', '..');

/** Directories that are never ours to license. */
const SKIP_DIRS = new Set(['node_modules', 'dist', '.git', 'data', 'public', '.claude']);

/**
 * Files that are deliberately exempt, each for a reason that is not "we forgot".
 *
 *  - LICENSE is the licence text itself; prefixing it would corrupt it.
 *  - A lockfile is generated by npm and has no comment syntax at all.
 *  - index.html carries its header after the `<!doctype html>` line, which must come
 *    first — so it is checked by the "somewhere in the first few lines" rule below
 *    rather than exempted; it is named here only to document that it is not forgotten.
 */
const EXEMPT = new Set(['LICENSE', 'package-lock.json']);

/** Extensions we license, mapped to the comment token their header must start with. */
const COMMENT: Record<string, string[]> = {
  '.ts': ['//'],
  '.tsx': ['//'],
  '.js': ['//'],
  '.cjs': ['//'],
  '.mjs': ['//'],
  '.css': ['/*'],
  '.yml': ['#'],
  '.yaml': ['#'],
  '.sh': ['#'],
  '.md': ['<!--'],
  '.html': ['<!--'],
  '.svg': ['<!--'],
};

function licensedFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...licensedFiles(full));
      continue;
    }
    if (EXEMPT.has(entry.name)) continue;
    const ext = path.extname(entry.name).toLowerCase();
    const named = entry.name === 'Dockerfile' || entry.name.startsWith('Dockerfile.');
    if (!named && !(ext in COMMENT)) continue;
    out.push(path.relative(REPO, full).split(path.sep).join('/'));
  }
  return out;
}

/** The header must be at the very top — or, for a document with a mandatory first line
 *  (`<!doctype html>`, a shebang), within the first few. Anything further down is a
 *  header a reader will not see. */
const HEAD_LINES = 4;

test('every source file declares AGPL-3.0-only and the copyright holder', () => {
  const missingSpdx: string[] = [];
  const missingCopyright: string[] = [];
  const wrongLicence: string[] = [];

  for (const rel of licensedFiles(REPO)) {
    const head = fs.readFileSync(path.join(REPO, rel), 'utf8').split(/\r?\n/).slice(0, HEAD_LINES).join('\n');
    const spdx = /SPDX-License-Identifier:\s*(\S+)/.exec(head);
    if (!spdx) {
      missingSpdx.push(rel);
      continue;
    }
    // A file that declares a DIFFERENT licence is worse than one declaring none: it is
    // an affirmative claim, and it would be believed.
    if (spdx[1] !== 'AGPL-3.0-only') wrongLicence.push(`${rel} (says ${spdx[1]})`);
    if (!/Copyright \(C\) \d{4} OpenMasjid-Solutions/.test(head)) missingCopyright.push(rel);
  }

  assert.deepEqual(wrongLicence, [], `these files declare a licence other than AGPL-3.0-only:\n  ${wrongLicence.join('\n  ')}`);
  assert.deepEqual(missingSpdx, [], `these files have no SPDX header in their first ${HEAD_LINES} lines:\n  ${missingSpdx.join('\n  ')}`);
  assert.deepEqual(missingCopyright, [], `these files have an SPDX header but no copyright line:\n  ${missingCopyright.join('\n  ')}`);
});

test('the walk actually found this repository, not an empty directory', () => {
  // A guard on the guard. If the path resolution above ever broke, every assertion in
  // this file would pass vacuously and the licence check would silently stop existing —
  // which is the same failure mode testFileCoverage.test.ts exists to prevent.
  const found = licensedFiles(REPO);
  assert.ok(found.length > 15, `expected to walk the whole repo, found only ${found.length} files`);
  assert.ok(found.includes('manifest.yaml'), 'manifest.yaml should be in the walk');
  assert.ok(found.includes('server/src/index.ts'), 'the server entry point should be in the walk');
  assert.ok(
    found.some((f) => f.startsWith('.github/workflows/')),
    'the CI workflows should be in the walk',
  );
});

test('package.json files all declare the AGPL licence field', () => {
  // The SPDX comment cannot live in JSON, so the `license` field is where the same claim
  // is made — and APP_LICENSING.md §6 requires it of every package.json in the repo.
  const found: string[] = [];
  const walk = (dir: string) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (SKIP_DIRS.has(entry.name)) continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name === 'package.json') found.push(full);
    }
  };
  walk(REPO);
  assert.ok(found.length >= 2, 'expected at least the server and web package.json');
  for (const p of found) {
    const pkg = JSON.parse(fs.readFileSync(p, 'utf8')) as { license?: string };
    assert.equal(pkg.license, 'AGPL-3.0-only', `${path.relative(REPO, p)} must declare "license": "AGPL-3.0-only"`);
  }
});
